from __future__ import annotations

import asyncio
import json
import re
import urllib.request
from pathlib import Path
from typing import Protocol

from temporalio import activity

from ..policy.rules import ArtifactEvidence, PolicyViolation, require_deployable_artifact
from .provision_and_deploy import DeliveryInput, DeliveryResult


_SAFE_EVIDENCE_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")


class EvidenceStore(Protocol):
    def load(self, pipeline_run_id: str) -> dict[str, object]: ...


class RuntimeRunner(Protocol):
    async def deploy(self, delivery: DeliveryInput) -> str: ...

    async def health_check(self, delivery: DeliveryInput) -> bool: ...

    async def rollback(self, delivery: DeliveryInput) -> None: ...


class FileEvidenceStore:
    """Read immutable CI evidence through a local-substitutable filesystem seam."""

    def __init__(self, root: Path) -> None:
        self.root = root.resolve()

    def load(self, pipeline_run_id: str) -> dict[str, object]:
        if not _SAFE_EVIDENCE_ID.fullmatch(pipeline_run_id):
            raise PolicyViolation("invalid pipeline run id for evidence lookup")
        path = self.root / f"{pipeline_run_id}.json"
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except FileNotFoundError as exc:
            raise PolicyViolation(f"security evidence missing for pipeline run {pipeline_run_id}") from exc
        except (OSError, json.JSONDecodeError) as exc:
            raise PolicyViolation(f"security evidence is unreadable for pipeline run {pipeline_run_id}") from exc
        if not isinstance(payload, dict):
            raise PolicyViolation("security evidence must be a JSON object")
        return payload


class DeliveryActivities:
    """Fail-closed delivery operations used by the Temporal worker."""

    def __init__(self, evidence_store: EvidenceStore, runtime_runner: RuntimeRunner) -> None:
        self.evidence_store = evidence_store
        self.runtime_runner = runtime_runner

    @activity.defn(name="validate_artifact")
    async def validate_artifact(self, delivery: DeliveryInput) -> None:
        evidence = self.evidence_store.load(delivery.pipeline_run_id)
        if evidence.get("applicationId") != delivery.application_id:
            raise PolicyViolation("security evidence application does not match delivery")
        if evidence.get("artifactDigest") != delivery.artifact_digest:
            raise PolicyViolation("security evidence digest does not match delivery")
        scan = evidence.get("vulnerabilityScan")
        signature = evidence.get("signature")
        sbom = evidence.get("sbom")
        if not isinstance(sbom, dict) or sbom.get("generatedBy") != "syft" or not isinstance(sbom.get("location"), str) or not sbom.get("location"):
            raise PolicyViolation("SBOM evidence must be generated by Syft and include a location")
        if not isinstance(scan, dict) or scan.get("scanner") != "trivy" or scan.get("status") != "passed":
            raise PolicyViolation("Trivy vulnerability scan evidence is missing or failed")
        try:
            critical_count = int(scan.get("critical", 0))
            high_count = int(scan.get("high", 0))
        except (TypeError, ValueError) as exc:
            raise PolicyViolation("Trivy vulnerability counts are invalid") from exc
        if critical_count > 0 or high_count > 0:
            raise PolicyViolation("artifact contains critical or high vulnerabilities")
        if not isinstance(signature, dict) or signature.get("provider") != "cosign" or signature.get("verified") is not True:
            raise PolicyViolation("Cosign signature evidence is missing or unverified")
        require_deployable_artifact(
            ArtifactEvidence(
                digest=delivery.artifact_digest,
                sbom_present=isinstance(sbom, dict) and bool(sbom.get("location")),
                vulnerability_scan_passed=isinstance(scan, dict) and scan.get("status") == "passed",
                signature_verified=isinstance(signature, dict) and signature.get("verified") is True,
            )
        )
        if evidence.get("decision") != "allow":
            raise PolicyViolation(str(evidence.get("reason") or "artifact policy decision is deny"))

    @activity.defn(name="deploy")
    async def deploy(self, delivery: DeliveryInput) -> DeliveryResult:
        deployment_id = await self.runtime_runner.deploy(delivery)
        return DeliveryResult(
            deployment_id=deployment_id,
            status="deploying",
            artifact_digest=delivery.artifact_digest,
        )

    @activity.defn(name="health_check")
    async def health_check(self, delivery: DeliveryInput) -> bool:
        return await self.runtime_runner.health_check(delivery)

    @activity.defn(name="rollback")
    async def rollback(self, delivery: DeliveryInput) -> None:
        await self.runtime_runner.rollback(delivery)


class AnsibleRuntimeRunner:
    """Invoke the checked-in Ansible adapters without exposing command details to workflows."""

    _PLAYBOOKS = {
        "docker": "deploy-docker.yml",
        "kubernetes": "deploy-kubernetes.yml",
        "systemd": "deploy-systemd.yml",
    }

    def __init__(self, project_root: Path, inventory: Path, executable: str = "ansible-playbook") -> None:
        self.project_root = project_root.resolve()
        self.inventory = inventory.resolve()
        self.executable = executable

    def command_for(self, action: str, delivery: DeliveryInput) -> list[str]:
        try:
            playbook_name = self._PLAYBOOKS[delivery.runtime]
        except KeyError as exc:
            raise ValueError(f"unsupported runtime: {delivery.runtime}") from exc
        if action not in {"deploy", "rollback"}:
            raise ValueError(f"unsupported delivery action: {action}")
        extra_vars: dict[str, object] = {
            "netci_action": action,
            "application_id": delivery.application_id,
            "pipeline_run_id": delivery.pipeline_run_id,
            "target_environment": delivery.environment,
            "artifact_digest": delivery.artifact_digest,
            "release_name": delivery.release_name,
            **delivery.parameters,
        }
        playbook = self.project_root / "deploy" / "ansible" / "playbooks" / playbook_name
        return [
            self.executable,
            "-i",
            str(self.inventory),
            str(playbook),
            "--extra-vars",
            json.dumps(extra_vars, sort_keys=True),
        ]

    async def _run(self, command: list[str]) -> None:
        process = await asyncio.create_subprocess_exec(
            *command,
            cwd=self.project_root,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await process.communicate()
        if process.returncode != 0:
            detail = (stderr or stdout).decode(errors="replace")[-4000:]
            raise RuntimeError(f"runtime adapter failed with exit {process.returncode}: {detail}")

    async def deploy(self, delivery: DeliveryInput) -> str:
        await self._run(self.command_for("deploy", delivery))
        return f"deployment-{delivery.pipeline_run_id}"

    async def health_check(self, delivery: DeliveryInput) -> bool:
        health_url = delivery.parameters.get("health_url")
        if not isinstance(health_url, str) or not health_url.startswith(("http://", "https://")):
            return False

        def request() -> bool:
            try:
                with urllib.request.urlopen(health_url, timeout=5) as response:
                    return 200 <= response.status < 300
            except OSError:
                return False

        return await asyncio.to_thread(request)

    async def rollback(self, delivery: DeliveryInput) -> None:
        await self._run(self.command_for("rollback", delivery))

