apiVersion: v1
kind: Service
metadata:
  name: {{ include "netci.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netci.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "netci.fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "netci.fullname" . }}-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
