apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-controller
  namespace: {{ .Values.jenkins.buildNamespace | default "netci-build" | quote }}
  labels:
    {{- include "netci.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: {{ .Values.jenkins.buildNamespace | default "netci-build" | quote }}
  labels:
    {{- include "netci.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-controller
  namespace: {{ .Values.jenkins.buildNamespace | default "netci-build" | quote }}
  labels:
    {{- include "netci.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-controller
  namespace: {{ .Values.jenkins.buildNamespace | default "netci-build" | quote }}
  labels:
    {{- include "netci.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: jenkins-controller
    namespace: {{ .Values.jenkins.buildNamespace | default "netci-build" | quote }}
roleRef:
  kind: Role
  name: jenkins-controller
  apiGroup: rbac.authorization.k8s.io
