apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netci.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netci.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "netci.fullname" . }}-worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "netci.fullname" . }}-worker
  template:
    metadata:
      labels:
        {{- include "netci.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "netci.fullname" . }}-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "netci.fullname" . }}-config
            - secretRef:
                name: {{ include "netci.fullname" . }}-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
