apiVersion: netci.io/v1alpha1
kind: DeliveryTemplate
metadata:
  name: kubernetes-ci-cd-v1
spec:
  runtime: kubernetes
  artifactKind: container-image
  deploy:
    adapter: kubernetes
    runner: ansible
    module: kubernetes.core.helm
  stages:
    - checkout
    - unit-test
    - build
    - sbom
    - vulnerability-scan
    - sign
    - publish
    - deploy
    - health-check
  environments: [dev, staging, prod]
  productionApproval: required
