{{- if and .Values.traits (and .Values.traits.kedaAutoscaling .Values.traits.kedaAutoscaling.enabled) -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "sample-kubernetes-app.fullname" . }}-keda
  labels:
    app.kubernetes.io/name: {{ include "sample-kubernetes-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    netci.io/trait: keda-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sample-kubernetes-app.fullname" . }}
  minReplicaCount: {{ .Values.traits.kedaAutoscaling.minReplicas | default 1 }}
  maxReplicaCount: {{ .Values.traits.kedaAutoscaling.maxReplicas | default 5 }}
  cooldownPeriod: {{ .Values.traits.kedaAutoscaling.cooldownPeriod | default 300 }}
  pollingInterval: {{ .Values.traits.kedaAutoscaling.pollingInterval | default 30 }}
  triggers:
    {{- if .Values.traits.kedaAutoscaling.triggers }}
    {{- toYaml .Values.traits.kedaAutoscaling.triggers | nindent 4 }}
    {{- else }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: "80"
    {{- end }}
{{- end }}
