apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-kubernetes-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sample-kubernetes-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    netci.io/track: {{ include "sample-kubernetes-app.track" . | quote }}
    netci.io/environment: {{ .Values.environment | quote }}
    {{- if .Values.netci.applicationId }}
    netci.io/application: {{ .Values.netci.applicationId | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "sample-kubernetes-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
