apiVersion: v1
kind: Namespace
metadata:
  name: netci-build
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: netci-build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-agent
  namespace: netci-build
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent
  namespace: netci-build
subjects:
  - kind: ServiceAccount
    name: jenkins-agent
    namespace: netci-build
roleRef:
  kind: Role
  name: jenkins-agent
  apiGroup: rbac.authorization.k8s.io
