import { useState } from 'react'
import {
  Activity, ArrowLeft, Check, CheckCircle2, Copy, History, KeyRound, Minus,
  MoreHorizontal, Pencil, Plus, Search, Settings as Cog, SlidersHorizontal,
  Trash2, UserPlus, Users,
} from 'lucide-react'
import { Modal } from './PortalShell'
import { auditEvents, dcimModules, modules, type SettingsTab } from './portalData'

const pipelineTabs = ['CI', 'CD Dev', 'CD Staging', 'CD Prod', 'Automation Test']

type SettingsModule = { name: string; code: string; type: string; description: string; repository: string }

function GeneralSettings({ module }: { module: SettingsModule }) {
  return <><div className="settings-toolbar"><div><h2>General</h2><p>Basic information synced with DCIM where applicable.</p></div></div><section className="panel settings-card"><div className="form-grid"><label className="field full"><span>Display name</span><input defaultValue={module.name} /></label><label className="field"><span>Module code</span><input value={module.code} readOnly /></label><label className="field"><span>Module type</span><select defaultValue={module.type}><option>Backend</option><option>Frontend</option><option>Worker</option><option>Gateway</option></select></label><label className="field full"><span>Description</span><textarea defaultValue={module.description} /></label><label className="field full"><span>Git repository</span><input value={module.repository} readOnly /></label></div><div className="settings-save"><button className="primary-button"><Check size={16} />Save changes</button></div></section><section className="danger-zone"><h3>Danger zone</h3><div><span><strong>Remove module</strong><p>Disconnect the module from Release Portal. Delivery history will be preserved.</p></span><button className="danger-button">Remove module</button></div></section></>
}

function PipelineSettings() {
  const [tab, setTab] = useState('CI')
  const [mode, setMode] = useState<'visual' | 'code'>('visual')
  const [stages, setStages] = useState(['Checkout', 'Install dependencies', 'Lint', 'Unit test', 'Type check', 'Code analysis', 'Security scan', 'Build', 'Publish artifact'])
  const yaml = ['pipeline:', `  name: ${tab.toLowerCase().replace(/ /g, '-')}`, '  runner: docker-linux', '  branches:', '    - main', '  stages:', '    - checkout', '    - install-dependencies', '    - unit-test', '    - security-scan', '    - build', '    - publish-artifact'].join('\n')
  return <><div className="settings-pipeline-tabs">{pipelineTabs.map((item) => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><div className="settings-toolbar"><div><h2>{tab} pipeline</h2><p>Configure branches, runner and delivery stages.</p></div><div className="segmented compact"><button className={mode === 'visual' ? 'active' : ''} onClick={() => setMode('visual')}>Visual</button><button className={mode === 'code' ? 'active' : ''} onClick={() => setMode('code')}>As code</button></div></div>{mode === 'visual' ? <><div className="form-grid settings-form"><label className="field"><span>Source branch</span><input defaultValue={tab === 'CI' ? 'main, merge_requests' : tab.includes('Prod') ? 'tags/v*' : 'develop'} /></label><label className="field"><span>Runner</span><select><option>Runner 01 · docker-linux</option><option>Runner 02 · on-prem</option></select></label></div><div className="stage-list"><div className="section-heading"><h3>Stages</h3><button className="secondary-button" onClick={() => setStages([...stages, 'Custom stage'])}><Plus size={15} />Add stage</button></div>{stages.map((stage, index) => <div key={`${stage}-${index}`}><span className="drag-handle">⠿</span><span className="stage-number">{index + 1}</span><strong>{stage}</strong><small>{index < 2 ? 'Source' : index < 6 ? 'Test' : 'Build'}</small><button aria-label={`Sửa ${stage}`}><Pencil size={15} /></button><button aria-label={`Xóa ${stage}`} onClick={() => setStages(stages.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={15} /></button></div>)}</div><div className="settings-save"><button className="primary-button"><Check size={16} />Save pipeline</button></div></> : <div className="code-editor"><div><span>pipeline.yml</span><button><Copy size={15} />Copy</button></div><pre>{yaml}</pre></div>}</>
}

function AccessSettings() {
  const [tab, setTab] = useState('CI')
  const [grant, setGrant] = useState(false)
  const users: Array<[string, string, boolean, boolean, boolean]> = [['Admin', 'Owner', true, true, true], ['TrungTT', 'Maintainer', true, true, true], ['LinhPT', 'Developer', false, true, true], ['HaiNM', 'Viewer', false, false, true]]
  return <><div className="settings-pipeline-tabs">{pipelineTabs.map((item) => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><div className="settings-toolbar"><div><h2>{tab} access</h2><p>Control who can edit, trigger and view pipeline logs.</p></div><button className="primary-button" onClick={() => setGrant(true)}><UserPlus size={16} />Grant access</button></div><section className="panel table-panel"><div className="data-table access-table"><div className="table-row table-head"><span>User</span><span>Role</span><span>Edit</span><span>Trigger</span><span>View logs</span><span /></div>{users.map(([name, role, edit, trigger, logs]) => <div className="table-row" key={name}><span className="user-cell"><i className="avatar">{name.slice(0, 2).toUpperCase()}</i><strong>{name}</strong></span><span>{role}</span>{[edit, trigger, logs].map((allowed, index) => <span className={allowed ? 'permission-yes' : 'permission-no'} key={index}>{allowed ? <CheckCircle2 size={17} /> : <Minus size={17} />}</span>)}<button className="row-more"><MoreHorizontal size={17} /></button></div>)}</div></section>{grant && <Modal title="Grant pipeline access" description={`Add a user to ${tab} pipeline.`} onClose={() => setGrant(false)} footer={<><button className="secondary-button" onClick={() => setGrant(false)}>Cancel</button><button className="primary-button" onClick={() => setGrant(false)}>Grant access</button></>}><label className="field"><span>Search people</span><div className="input-with-icon"><Search size={16} /><input placeholder="Name or email" /></div></label><label className="field"><span>Role</span><select><option>Developer</option><option>Maintainer</option><option>Viewer</option></select></label></Modal>}</>
}

function TeamSettings() {
  const users = [['AD', 'Admin', 'admin@netchat.io', 'Owner'], ['TT', 'TrungTT', 'trung.tt@netchat.io', 'Maintainer'], ['LP', 'LinhPT', 'linh.pt@netchat.io', 'Developer'], ['HN', 'HaiNM', 'hai.nm@netchat.io', 'Viewer']]
  return <><div className="settings-toolbar"><div><h2>Team & Access</h2><p>Manage module members and role-based permissions.</p></div><button className="primary-button"><UserPlus size={16} />Add member</button></div><section className="panel team-list">{users.map(([initials, name, email, role]) => <div key={email}><span className="avatar">{initials}</span><span><strong>{name}</strong><small>{email}</small></span><select defaultValue={role}><option>Owner</option><option>Maintainer</option><option>Developer</option><option>Viewer</option></select><button className="row-more"><MoreHorizontal size={17} /></button></div>)}</section><div className="role-guide">{[['Owner', 'Full access, including members and settings.'], ['Maintainer', 'Edit pipelines, trigger runs and manage versions.'], ['Developer', 'Trigger allowed pipelines and view logs.'], ['Viewer', 'Read-only access to module delivery data.']].map(([role, description]) => <div key={role}><strong>{role}</strong><p>{description}</p></div>)}</div></>
}

function ActivitySettings({ hasHistory }: { hasHistory: boolean }) {
  return <><div className="settings-toolbar"><div><h2>Activity Log</h2><p>Auditable changes and pipeline operations for this module.</p></div><select><option>All actions</option><option>Pipeline</option><option>Access</option><option>Version</option></select></div><section className="panel table-panel"><div className="data-table audit-table"><div className="table-row table-head"><span>Action</span><span>User</span><span>Pipeline</span><span>Detail</span><span>Time</span></div>{hasHistory && auditEvents.map((event) => <div className="table-row" key={`${event.action}-${event.time}`}><span className="audit-action"><Activity size={15} />{event.action}</span><span>{event.user}</span><span>{event.pipeline}</span><span>{event.detail}</span><span>{event.time}</span></div>)}</div>{!hasHistory && <div className="empty-table"><History size={22} /><strong>No activity yet</strong><span>Module actions will appear here after its first configuration change or pipeline run.</span></div>}</section></>
}

export function ModuleSettings({ systemId, moduleId, onClose }: { systemId: string; moduleId: string; onClose: () => void }) {
  const [tab, setTab] = useState<SettingsTab>('general')
  const seed = modules.find((item) => item.id === moduleId)
  const dcim = dcimModules.find((item) => item.id === moduleId)
  const module: SettingsModule = { name: seed?.name ?? dcim?.name ?? moduleId, code: dcim?.code ?? moduleId.toUpperCase().replace(/-/g, '_'), type: seed?.type ?? dcim?.type ?? 'Backend', description: seed?.description ?? `${dcim?.name ?? moduleId} imported from DCIM.`, repository: dcim?.repo ?? '' }
  const items: Array<[SettingsTab, string, typeof Cog]> = [['general', 'General', Cog], ['pipelines', 'Pipelines', SlidersHorizontal], ['pipeline-access', 'Pipeline Access', KeyRound], ['team', 'Team & Access', Users], ['activity', 'Activity Log', History]]
  return <div className="settings-page"><div className="settings-top"><button className="back-button" onClick={onClose}><ArrowLeft size={16} />Back to {module.name}</button><div><h1>Module Settings</h1><p>{module.name} · {systemId}</p></div></div><div className="settings-layout"><aside>{items.map(([id, label, Icon]) => <button className={tab === id ? 'active' : ''} onClick={() => setTab(id)} key={id}><Icon size={17} />{label}</button>)}</aside><main>{tab === 'general' && <GeneralSettings module={module} />}{tab === 'pipelines' && <PipelineSettings />}{tab === 'pipeline-access' && <AccessSettings />}{tab === 'team' && <TeamSettings />}{tab === 'activity' && <ActivitySettings hasHistory={Boolean(seed)} />}</main></div></div>
}
