#!/usr/bin/env bash
# Install the run queue on the lab cluster for cell-b.
#
#   NETCI_IMAGE=172.17.0.1:8930/netci/netci@sha256:<digest> lab/queue.sh
#
# Secrets are generated into .netci-gate/lab/queue and reach the cluster through files:
#   - the database password;
#   - the API token of cell-b's `netci` user, generated by that user through Jenkins;
#   - a client token for the lab's probes, of which only the SHA-256 is in the configuration.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE="${ROOT}/.netci-gate/lab"
Q="${STATE}/queue"
export KUBECONFIG="${STATE}/kubeconfig"
: "${NETCI_IMAGE:?set NETCI_IMAGE to the netCI image (a Harbor reference)}"
PG_IMAGE="${PG_IMAGE:-172.17.0.1:8930/mirror/postgres:16.15-alpine3.24}"
JENKINS="http://192.168.122.211:30081"   # cell-b's NodePort, from the host
mkdir -m 700 -p "${Q}"
( umask 077
  [[ -s "${Q}/db-password" ]] || openssl rand -hex 24 > "${Q}/db-password"
  [[ -s "${Q}/client-token" ]] || openssl rand -hex 32 > "${Q}/client-token"
  # Each cell's controller records netciOnce markers (ADR-065) with its own token, which can do
  # nothing else; lab/spike/deploy.sh puts it in the cell's secret.
  for cell in cell-a cell-b; do [[ -s "${Q}/once-${cell}-token" ]] || openssl rand -hex 32 > "${Q}/once-${cell}-token"; done
  printf 'postgresql://netci:%s@netci-pg.netci-system.svc:5432/netci?sslmode=disable' "$(cat "${Q}/db-password")" > "${Q}/db-url"
  # The netci user makes its own API token: API tokens are exempt from Jenkins' CSRF crumb,
  # a password is not. Made once; kept with the other secrets.
  if [[ ! -s "${Q}/cell-b-token" ]]; then
    python3 - "${JENKINS}" "${STATE}/cell-netci-password" "${Q}/cell-b-token" <<'PY'
import base64, http.cookiejar, json, sys, urllib.request
base, pwfile, out = sys.argv[1:]
auth = "Basic " + base64.b64encode(f"netci:{open(pwfile).read().strip()}".encode()).decode()
op = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(http.cookiejar.CookieJar()))
def call(path, data=None, headers={}):
    req = urllib.request.Request(base + path, data=data, headers={"Authorization": auth, **headers})
    return json.loads(op.open(req, timeout=20).read())
crumb = call("/crumbIssuer/api/json")
r = call("/user/netci/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken",
         data=b"newTokenName=netci-queue", headers={crumb["crumbRequestField"]: crumb["crumb"]})
open(out, "w").write(r["data"]["tokenValue"])
PY
  fi
)
( umask 077; [[ -s "${Q}/gitlab-hook-secret" ]] || openssl rand -hex 24 > "${Q}/gitlab-hook-secret" )
hash="$(tr -d '\n' < "${Q}/client-token" | sha256sum | cut -d' ' -f1)"
hook_hash="$(tr -d '\n' < "${Q}/gitlab-hook-secret" | sha256sum | cut -d' ' -f1)"
once_a="$(tr -d '\n' < "${Q}/once-cell-a-token" | sha256sum | cut -d' ' -f1)"
once_b="$(tr -d '\n' < "${Q}/once-cell-b-token" | sha256sum | cut -d' ' -f1)"
# The lab GitLab's pushes to main of any project start webhook-probe (lab/spike/webhook_probe.py).
cat > "${Q}/config.json" <<JSON
{"cells": {"cell-b": {"url": "http://jenkins.cell-b.svc.cluster.local:8080", "credentials": "/etc/netci/cells/cell-b", "budget": 50}},
 "routes": [{"prefix": "", "cell": "cell-b"}],
 "clients": {"lab-probe": {"tokenSha256": "${hash}", "jobs": [""]},
             "cell-a": {"tokenSha256": "${once_a}", "once": true}, "cell-b": {"tokenSha256": "${once_b}", "once": true}},
 "hooks": {"lab-gitlab": {"provider": "gitlab", "tokenSha256": "${hook_hash}", "client": "lab-probe",
   "rules": [{"event": "push", "ref": "main", "job": "webhook-probe",
              "parameters": {"GIT_SHA": "{{sha}}", "BRANCH": "{{ref_name}}", "BY": "{{user}}"}}]}}}
JSON
kubectl apply -f "${ROOT}/lab/priorities.yaml" >/dev/null
kubectl create namespace netci-system --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl -n netci-system create secret generic harbor-pull --type kubernetes.io/dockerconfigjson \
  --from-file=.dockerconfigjson="${STATE}/harbor-pull.json" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl -n netci-system create secret generic netci-queue-db --from-file=password="${Q}/db-password" \
  --from-file=url="${Q}/db-url" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
printf 'netci' > "${Q}/cell-b-user"
kubectl -n netci-system create secret generic netci-queue-cells --from-file=cell-b-user="${Q}/cell-b-user" \
  --from-file=cell-b-token="${Q}/cell-b-token" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl -n netci-system create configmap netci-queue --from-file=config.json="${Q}/config.json" \
  --dry-run=client -o yaml | kubectl apply -f - >/dev/null
sed -e "s|NETCI_IMAGE|${NETCI_IMAGE}|" -e "s|PG_IMAGE|${PG_IMAGE}|" "${ROOT}/lab/queue/queue.yaml" | kubectl apply -f - >/dev/null
kubectl -n netci-system rollout status statefulset/netci-pg --timeout=300s
kubectl -n netci-system rollout restart deployment/netci-queue >/dev/null
kubectl -n netci-system rollout status deployment/netci-queue --timeout=300s
