apiVersion: netci.io/v1alpha1
kind: DeliveryTemplate
metadata:
  name: container-ci-cd-v1
spec:
  runtime: docker
  artifactKind: container-image
  deploy:
    adapter: docker
    runner: ansible
  stages:
    - checkout
    - unit-test
    - build
    - sbom
    - vulnerability-scan
    - sign
    - publish
    - deploy
    - health-check
  environments: [dev, staging, prod]
  productionApproval: required
